### ISSUE TITLE
Scrollcontroller not attached to an scroll views

### ISSUE THREAD

**Issue by kamami** [bxqm/sliding_sheet#104]
After calling controller.hide() I am getting this error:

` [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (10350): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (10350): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (10350): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
E/flutter (10350): #3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:116:24)
E/flutter (10350): #4      _SlidingSheetScrollController.snapToExtent.<anonymous closure> (package:sliding_sheet/src/scrolling.dart:133:16)
E/flutter (10350): #5      _rootRun (dart:async/zone.dart:1420:47)
E/flutter (10350): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (10350): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:203:18)
E/flutter (10350): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:737:39)
E/flutter (10350): #9      Future._propagateToListeners (dart:async/future_impl.dart:793:11)
E/flutter (10350): #10     Future._propagateToListeners (dart:async/future_impl.dart:692:9)
E/flutter (10350): #11     Future._completeWithValue (dart:async/future_impl.dart:602:5)
E/flutter (10350): #12     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:640:7)
E/flutter (10350): #13     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (10350): #14     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (10350): #15     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (10350): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (10350): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (10350): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
`

This is my code so far:

                `class GlobalPlayerWrapper extends StatelessWidget {
                  final Widget child;
                
                  GlobalPlayerWrapper({required this.child});
                
                  SheetController controller = SheetController();
                
                  void snapToClose() {
                    controller.hide();
                  }
                
                  @override
                  Widget build(BuildContext context) {
                    return SlidingSheet(
                        controller: controller,
                        snapSpec: SnapSpec(
                            // Enable snapping. This is true by default.
                            snap: true,
                            // Set custom snapping points.
                            snappings: [56, 500],
                            // Define to what the snappings relate to. In this case,
                            // the total available space that the sheet can expand to.
                            positioning: SnapPositioning.pixelOffset,
                            initialSnap: 0),
                
                        // The body widget will be displayed under the SlidingSheet
                        // and a parallax effect can be applied to it.
                        body: child,
                        builder: (context, state) {
                          // This is the content of the sheet that will get
                          // scrolled, if the content is bigger than the available
                          // height of the sheet.
                
                          return Container();
                        });
                  }
                }`

Any idea what I am doing wrong?
I am using the latest package version and flutter 2.5.2.

**Comment by mislavlukach** [comment]
Same thing here. It happens even if you remove the controller from your widget. 
I don't think this happened in the past with this package. 
Did you manage to find the bug in the sliding_sheet package?

**Comment by markbulingit** [comment]
Any update?
